---
title: "Skin tape striping - data analysis"
author: "Tu Hu"
date: "1/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
reads <- 
  tibble(fn = list.dirs("../data/") %>% grep("\\d{1}_S\\d{1}_L00\\d{1}$", ., value = T)) %>% 
  mutate(read = paste0(fn, "/output.dge.reads.detailed.txt"),
         read = map(read, readr::read_tsv, show_col_types=FALSE),
         lib_size = map(read, ~ .x[,-1:-2] %>% colSums),
         batch = fn %>% str_extract("\\d{1}(?=\\_S)"),
         lane = fn %>% str_extract("L00\\d{1}"),
         sample_n = map(lib_size, names))

lib_size <- reads %>% select(lib_size, batch) %>% group_by(batch) %>% nest() %>% 
  mutate(lib_size = map(data, ~ .x[[1]] %>% reduce(`+`)))

libsize_g <- 
  reads %>% select(batch, lane, lib_size, sample_n) %>% 
  unnest() %>% 
  ggplot(aes(sample_n)) + geom_bar(aes(weight=lib_size)) +
  facet_grid(lane~batch, scales = "free") + scale_y_log10() + 
  theme(axis.text.x = element_text(angle = 90))
ggsave("../_tmp/counts_sample.jpg", libsize_g, width = 21, height = 7)

counts <-
  reads %>% select(batch, read) %>% 
  mutate(read = map(read, ~ .x[,-1:-2])) %>% 
  group_by(batch) %>% nest() %>% 
  mutate(read = map(data, ~ .x[[1]] %>% reduce(`+`))) %>% 
  pull(read) %>% reduce(cbind) %>% 
  cbind(reads$read[[1]][,1:2], .) %>% as_tibble(.name_repair = "unique")
         # read = map(read, ~ cbind(reads$read[[1]][,1:2], .x)))

```

```{r}
g <- counts$Gene_name
genes <- c(counts$Gene_name)

require(biomaRt)
mart <- useMart("ENSEMBL_MART_ENSEMBL")
mart <- useDataset("hsapiens_gene_ensembl", mart)
annotLookup <- getBM(
  mart = mart,
  attributes = c(
    "hgnc_symbol",
    "entrezgene_id",
    "ensembl_gene_id",
    "gene_biotype"),
  filter = "hgnc_symbol",
  values = g,
  uniqueRows=TRUE)
g_p <- annotLookup %>% filter(gene_biotype == "protein_coding") %>% pull(hgnc_symbol)

counts_g_p <- counts %>% filter(Gene_name %in% g_p)
counts_g_p %>% readr::write_csv("../data/counts_pcoding.csv")
```
